name: lino_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  file_picker: ^10.3.3
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.4.2
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.4.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  get: ^4.7.2
  go_router: ^16.2.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  logger: ^2.6.1
  mime: ^2.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.2
  timeago: ^3.7.1
  uuid: ^4.5.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700 
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 500

  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: true